# Generated by Django 4.2.13 on 2025-04-04 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodorder', '0003_alter_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('location', models.TextField()),
                ('menu_items', models.TextField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
