# Generated by Django 5.2 on 2025-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0005_alter_catering_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='catering',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='catering',
            name='menu_items',
            field=models.ManyToManyField(related_name='caterings', to='foodorder.menuitem'),
        ),
    ]
